server:
  port: 8081
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVER
          uri: ${AUTH_URL:http://localhost:8080}
          predicates:
            - Path=/api/v1/user/**,/api/v1/address/**
        - id: INVENTORY-SERVER
          uri: ${INVENTORY_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/item/**
        - id: ORDER-SERVER
          uri: ${ORDER_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/order/**
        - id: PAYMENT-SERVER
          uri: ${PAYMENT_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/payment/**
  main:
    web-application-type: reactive

SECURE_KEY: ${SECURE_KEY_STR:8Xc5HXT4fRYeGL5uLyNgaGg4vtMldmLhjtIvD2gLoK4=}
